controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_base_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    use_stamped_vel: false
    
    wheel_separation: 0.28
    wheel_radius: 0.045
    
    publish_rate: 50.0
    base_frame_id: base_footprint
    odom_frame_id: odom
    
    enable_odom_tf: false 
    
    cmd_vel_timeout: 0.5
    publish_cmd: true